### ISSUE TITLE
I can't test my model correctly

### ISSUE THREAD

**Issue by kareemgamalmahmoud** [MSiam/CV4Africa_Challenge_Baseline#1]
After training my model correctly, I tried to run the inference command, but I encountered some issues regarding the `text.txt` file.
The paths inside the file look like this: `"data_challenge/labels_4/tiles/test_00000.png"`, but the testing images are located inside the `images` folder, not the `labels_4` folder. 

After handling this, I faced a similar error that told me there is no `"data_challenge/images/tiles/test_00000.png"`, which has left me confused. I then copied the testing folder twice.

Now, I am facing this error:

`
File "/content/CV4Africa_Challenge_Baseline/spatial_apertheid_dataloader.py", line 116, in map_mask
    temp_mask[mask==cls] = self.cls_mapping[int(cls)]
KeyError: 46
`

I would appreciate any assistance in finding a better way to run the `inference.py` file.

**Comment by MSiam** [comment]
Hello Karim,  

      It seems to be related to the google cola setup so beyond that code. Since you already solved it and had a submission in our challenge, I am assuming you have already fixed it as such I am closing the issue.

Thanks.
